"""Pydantic models mirroring the TypeScript contract in ``frontend/src/types``."""

from .base import CamelModel, to_camel
from .memory import (
    FidelityMetrics,
    FrameFidelity,
    LatentPointRef,
    ReconstructedFrame,
    ReconstructionReport,
    ReconstructionStatus,
    SceneEstimate,
    SessionRecord,
    SessionSummary,
    SessionVersion,
    StimulusClip,
    StimulusSource,
    VisualFeatures,
)
from .neural import (
    LATENT_DIMENSIONS,
    FrequencyBand,
    LatentPoint,
    NeuralFrame,
    SignalQuality,
    SignalQualityGrade,
    Spectrum,
    SyncResult,
    VisualResponse,
)
from .pipeline import STAGE_ORDER, PipelineStageId, PipelineStageState, StageStatus
from .stream import (
    FrameEvent,
    LatentEvent,
    MetricsEvent,
    PipelineEvent,
    ProgressEvent,
    ReconstructionFrameEvent,
    ReportEvent,
    SessionClosedEvent,
    SessionOpenedEvent,
    StreamCommand,
    StreamErrorEvent,
    SyncEvent,
)

__all__ = [
    "CamelModel",
    "FidelityMetrics",
    "FrameEvent",
    "FrameFidelity",
    "FrequencyBand",
    "LATENT_DIMENSIONS",
    "LatentEvent",
    "LatentPoint",
    "LatentPointRef",
    "MetricsEvent",
    "NeuralFrame",
    "PipelineEvent",
    "PipelineStageId",
    "PipelineStageState",
    "ProgressEvent",
    "ReconstructedFrame",
    "ReconstructionFrameEvent",
    "ReconstructionReport",
    "ReconstructionStatus",
    "ReportEvent",
    "STAGE_ORDER",
    "SceneEstimate",
    "SessionClosedEvent",
    "SessionOpenedEvent",
    "SessionRecord",
    "SessionSummary",
    "SessionVersion",
    "SignalQuality",
    "SignalQualityGrade",
    "Spectrum",
    "StageStatus",
    "StimulusClip",
    "StimulusSource",
    "StreamCommand",
    "StreamErrorEvent",
    "SyncEvent",
    "SyncResult",
    "VisualFeatures",
    "VisualResponse",
    "to_camel",
]
