"""Memory library — stored sessions, search, bookmarks and export."""

from __future__ import annotations

from typing import List, Optional

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import PlainTextResponse

from ..models.base import CamelModel
from ..models.memory import SessionRecord, SessionSummary
from ..services.store import get_store

router = APIRouter(prefix="/api/library", tags=["library"])


class BookmarkRequest(CamelModel):
    bookmarked: bool


@router.get("/sessions", response_model=List[SessionSummary])
async def list_sessions(
    limit: int = Query(default=100, ge=1, le=500),
    q: Optional[str] = Query(default=None, description="Free-text search"),
    bookmarked: Optional[bool] = Query(default=None),
) -> List[SessionSummary]:
    """Stored sessions, newest first."""
    items = get_store().list(limit=limit, query=q)
    if bookmarked is not None:
        items = [s for s in items if s.bookmarked == bookmarked]
    return items


@router.get("/sessions/{session_id}", response_model=SessionRecord)
async def get_session(session_id: str) -> SessionRecord:
    record = get_store().get(session_id)
    if record is None:
        raise HTTPException(status_code=404, detail=f"No stored session {session_id}")
    return record


@router.delete("/sessions/{session_id}")
async def delete_session(session_id: str) -> dict:
    if not get_store().delete(session_id):
        raise HTTPException(status_code=404, detail=f"No stored session {session_id}")
    return {"deleted": session_id}


@router.post("/sessions/{session_id}/bookmark", response_model=SessionSummary)
async def set_bookmark(session_id: str, request: BookmarkRequest) -> SessionSummary:
    record = get_store().set_bookmark(session_id, request.bookmarked)
    if record is None:
        raise HTTPException(status_code=404, detail=f"No stored session {session_id}")
    return SessionSummary.model_validate(record.model_dump(by_alias=True))


@router.get("/sessions/{session_id}/report", response_class=PlainTextResponse)
async def export_report(session_id: str) -> str:
    """Human-readable Markdown report for a reconstruction."""
    record = get_store().get(session_id)
    if record is None:
        raise HTTPException(status_code=404, detail=f"No stored session {session_id}")
    return _render_report(record)


def _render_report(record: SessionRecord) -> str:
    m = record.metrics
    clip = record.clip

    lines: List[str] = [
        f"# {record.report.title}",
        "",
        f"**Session** `{record.id}` · version {record.version}  ",
        f"**Recorded** {record.created_at}  ",
        f"**Stimulus** {record.stimulus_title} "
        f"({clip.duration_seconds:.0f}s, {clip.scene_count} scenes, "
        f"{clip.grid_width}x{clip.grid_height} reconstruction grid)",
        "",
        "## Summary",
        "",
        record.report.summary,
        "",
        "## Fidelity",
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Composite fidelity | {m.composite * 100:.0f}% |",
        f"| Structural similarity (SSIM) | {m.ssim:.3f} |",
        f"| Peak SNR | {m.psnr:.1f} dB |",
        f"| Luminance tracking | r = {m.luminance_correlation:+.2f} |",
        f"| Motion tracking | r = {m.motion_correlation:+.2f} |",
        f"| Colour tracking | r = {m.color_correlation:+.2f} |",
        f"| Scene boundary F1 | {m.scene_cut_f1:.2f} |",
        f"| Spatial layout | r = {m.layout_correlation:+.2f} |",
        f"| Frames reconstructed | {record.frame_count} |",
        "",
        "## Findings",
        "",
    ]

    lines.extend(f"- {finding}" for finding in record.report.findings)
    lines.extend(["", "## Limitations", ""])
    lines.extend(f"- {limitation}" for limitation in record.report.limitations)

    if record.history:
        lines.extend(
            ["", "## Version history", "", "| Version | Fidelity | SSIM | Change |", "| --- | --- | --- | --- |"]
        )
        for version in record.history:
            lines.append(
                f"| {version.version} | {version.fidelity * 100:.0f}% | "
                f"{version.ssim:.3f} | {version.delta} |"
            )
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "*Generated by MindScape. Fidelity is measured against the reference clip "
            "the subject watched, at the native reconstruction resolution.*",
        ]
    )

    return "\n".join(lines)
